<?php $translate=Zend_Registry::get('Zend_Translate'); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="cache-control" content="no-cache"> 
<title>n2manager SMS | <?php print $translate->_("global_coverage"); ?></title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('body1.css'); ?>" />
</head>

<body>
<div id="container" class="terms">
 <div class="panel">
 <div class="row">
<h3><?php print $translate->_("global_coverage"); ?></h3>
<p><?php print $translate->_("global_coverage_text"); ?></p>
	<table class="genericTable">
	   <th><?php print $translate->_("country"); ?></th>
	   <th><?php print $translate->_("coverage"); ?></th>
			<?php foreach($this->countryList as $country) : ?>
			  <tr>
			      <td><b><?php print $country->getName();?></b></td>
				  <td><?php print $translate->_($country->getCoverage());?></td>
			</tr>
			<?php endforeach; ?>
		
</table>

<div class="row">
	<p><?php print $translate->_("note_text"); ?> </p>	  
 </div>

</div>
</div>
</div>
</body>
</html>