<?php $translate=Zend_Registry::get('Zend_Translate'); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>n2manager - Terms of use</title>
<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('body1.css'); ?>" />
</head>

<body>
<div id="container" class="terms">
 <div class="panel">
 <div class="row">
<h3 class="terms_header"><?php print $translate->_("terms_header1"); ?></h3>
<p>
 <?php print $translate->_("terms1"); ?>
</p>

<h3><?php print $translate->_("header2"); ?></h3>
<p>
<?php print $translate->_("terms2"); ?>
</p>

<p>
<?php print $translate->_("terms3"); ?>
</p>

<p>
<?php print $translate->_("terms4"); ?>
</p>

<p>
<?php print $translate->_("terms5"); ?>
</p>

<h3><?php print $translate->_("header3"); ?></h3>

<p>
<?php print $translate->_("terms6"); ?>
</p>
<p>
<?php print $translate->_("terms7"); ?>
</p>
<p>
<?php print $translate->_("terms8"); ?>
</p>
<p>
<?php print $translate->_("terms9"); ?>
</p>
<p>
<?php print $translate->_("terms10"); ?>
</p>
<p>
<?php print $translate->_("terms11"); ?>
</p>
<p>
<?php print $translate->_("terms12"); ?>
</p>
<p>
<?php print $translate->_("terms13"); ?>
</p>
<p>
<?php print $translate->_("terms14"); ?>
</p>
<p>
<?php print $translate->_("terms15"); ?>
</p>
<p>
<?php print $translate->_("terms16"); ?>
</p>

<p>
<?php print $translate->_("terms17"); ?>
</p>

<p>
<?php print $translate->_("terms18"); ?>
</p>

<p>
<?php print $translate->_("terms19"); ?>
</p>

<h3><?php print $translate->_("header4"); ?></h3>

<p>
<?php print $translate->_("terms20"); ?>
</p>

<p>
<?php print $translate->_("terms21"); ?>
</p>

<h3><?php print $translate->_("header5"); ?></h3>

<p>
<?php print $translate->_("terms22"); ?>
</p>
<p>
<?php print $translate->_("terms23"); ?>
</p>

<h3><?php print $translate->_("header6"); ?></h3>

<p>
<?php print $translate->_("terms24"); ?>
</p>
<p>
<?php print $translate->_("terms25"); ?>
</p>
<p>
<?php print $translate->_("terms26"); ?>
</p>
<p>
<?php print $translate->_("terms27"); ?>
</p>
<p>
<?php print $translate->_("terms28"); ?>
</p>

<p>
<?php print $translate->_("terms28_2"); ?>
</p>

<h3><?php print $translate->_("header7"); ?></h3>

<p>
<?php print $translate->_("terms29"); ?>
</p>
<p>
<?php print $translate->_("terms30"); ?>
</p>
<p>
<?php print $translate->_("terms31"); ?>
</p>
<p>
<?php print $translate->_("terms32"); ?>
</p>

<p>
<?php print $translate->_("terms33"); ?>
</p>
<p>
<?php print $translate->_("terms34"); ?>
</p>
<p>
<?php print $translate->_("terms35"); ?>
</p>
<p>
<?php print $translate->_("terms36"); ?>
</p>
<p>
<?php print $translate->_("terms37"); ?>
</p>

<h3><?php print $translate->_("header8"); ?></h3>
<p>
<?php print $translate->_("terms38"); ?>
</p>

<h3><?php print $translate->_("header9"); ?></h3>
<p><?php print $translate->_("terms39"); ?></p>
<p>
<?php print $translate->_("terms40"); ?>
</p>
<p>
<?php print $translate->_("terms41"); ?>
</p>
<p>
<?php print $translate->_("terms42"); ?>
</p>
<p>
<?php print $translate->_("terms43"); ?>
</p>
<p>
<?php print $translate->_("terms44"); ?>
</p>
<p>
<?php print $translate->_("terms45"); ?>
</p>
<p>
<?php print $translate->_("terms46"); ?>
</p>
<p>
<?php print $translate->_("terms47"); ?>
</p>
<p>
<?php print $translate->_("terms48"); ?><br/>
<?php print $translate->_("terms49"); ?><br/>
<?php print $translate->_("terms50"); ?><br/>
<?php print $translate->_("terms51"); ?>
</p>
</div>
</div>
</div>
</body>
</html>