<?php $translate=Zend_Registry::get('Zend_Translate'); ?>
<div id="bottomPanel" class="panel">

	<div class="row">	
	
	<?php if ($this->transaction->getStatus()==Constants::TRANS_RECEIVED){ ?>
	<h2><?php print $translate->_("payment_title1"); ?></h2>
	<h3><?php print $translate->_("payment_details"); ?></h3>
	 <p><?php print $translate->_("payment_details_desc1"); ?> <b><?php print $this->totalPrice; ?></b> <?php print $translate->_("payment_details_desc2"); ?></br>
    
	 <?php print $translate->_("payment_details_desc3"); ?> <b><?php print $this->product->getCreditsNumber(); ?></b> <?php print $translate->_("payment_details_desc4"); ?> 
	 <?php print $translate->_("payment_details_desc5"); ?> <b><? print $this->transaction->getShortPhone(); ?></b> <?php print $translate->_("payment_details_desc6"); ?> <b><?php print $this->country->getName();?></b>.
	 </p>
	 <p><?php print $translate->_("payment_details_desc7"); ?></p>
	 <p>
	  <?php print $translate->_("payment_thanks"); ?>
	 </p>
	 
			  
	<? } else { ?>
		<h2><?php print $translate->_("payment_title2"); ?></h2>
		<h3><?php print $translate->_("payment_reason"); ?></h3>
		 <p><?php print $this->paymentResponseMessage; ?></p> 
	<?php }?>
	</div>
	
</div>