<?php $translate=Zend_Registry::get('Zend_Translate'); ?>
<?php

$this->headTitle($translate->_("n2manager_title"));
$this->headTitle($translate->_("news_header1"));
$this->headTitle()->setSeparator(' | ');
?>

<div id="bottomPanel" class="panel">

			  
		 <div class="row">
			 <h2><?php print $translate->_("news_header1"); ?></h2>
			 <p><?php print $translate->_("news_intro"); ?></p>
			 
		 </div>
		    <div class="row">
			 <h3><?php print $translate->_("news_version1_1.0.24"); ?></h3>
			 <h4><?php print $translate->_("news_version1_1.0.24_date"); ?></h4>
			 <p><?php print $translate->_("news_version1_1.0.24_content_1"); ?></p>
			 <p><?php print $translate->_("news_version1_1.0.11_content_3"); ?>
			 <a href="<?php echo $this->url(array('lang'=>$translate->getLocale(),'controller'=>'contact','action'=>'form'),'default', null, true);?>"><?php print $translate->_("news_version1_1.0.7_content_5"); ?></a>
			</p>
	      </div>
		    <div class="row">
			 <h3><?php print $translate->_("news_version1_1.0.22"); ?></h3>
			 <h4><?php print $translate->_("news_version1_1.0.22_date"); ?></h4>
			 <p><?php print $translate->_("news_version1_1.0.22_content_1"); ?></p>
			 <p><?php print $translate->_("news_version1_1.0.11_content_3"); ?>
			 <a href="<?php echo $this->url(array('lang'=>$translate->getLocale(),'controller'=>'contact','action'=>'form'),'default', null, true);?>"><?php print $translate->_("news_version1_1.0.7_content_5"); ?></a>
			</p>
	      </div>
		  
		   <div class="row">
			 <h3><?php print $translate->_("news_version1_1.0.20"); ?></h3>
			 <h4><?php print $translate->_("news_version1_1.0.20_date"); ?></h4>
			 <p><?php print $translate->_("news_version1_1.0.20_content_1"); ?></p>
			 <p><?php print $translate->_("news_version1_1.0.20_content_2"); ?></p>
			 <p><?php print $translate->_("news_version1_1.0.20_content_3"); ?>
			 <a href="<?php echo $this->url(array('lang'=>$translate->getLocale(),'controller'=>'contact','action'=>'form'),'default', null, true);?>"><?php print $translate->_("news_version1_1.0.7_content_5"); ?></a>
			 <?php print $translate->_("news_version1_1.0.20_content_4"); ?>
			</p>
			
		 </div>
		 
		   <div class="row">
			 <h3><?php print $translate->_("news_version1_1.0.19"); ?></h3>
			 <h4><?php print $translate->_("news_version1_1.0.19_date"); ?></h4>
			 <p><?php print $translate->_("news_version1_1.0.19_content_1"); ?></p>
			 <p><?php print $translate->_("news_version1_1.0.19_content_2"); ?></p>
			 <p><?php print $translate->_("news_version1_1.0.11_content_3"); ?>
			 <a href="<?php echo $this->url(array('lang'=>$translate->getLocale(),'controller'=>'contact','action'=>'form'),'default', null, true);?>"><?php print $translate->_("news_version1_1.0.7_content_5"); ?></a>
			</p>
		 </div>
		 
		   <div class="row">
			
			 <h3><?php print $translate->_("news_version1_1.0.16"); ?></h3>
			 <h4><?php print $translate->_("news_version1_1.0.16_date"); ?></h4>
			 <p><?php print $translate->_("news_version1_1.0.16_content_1"); ?></p>
			 <p><?php print $translate->_("news_version1_1.0.11_content_3"); ?>
			 <a href="<?php echo $this->url(array('lang'=>$translate->getLocale(),'controller'=>'contact','action'=>'form'),'default', null, true);?>"><?php print $translate->_("news_version1_1.0.7_content_5"); ?></a>
			</p>
	      </div>
		 
		  <div class="row">
			
			 <h3><?php print $translate->_("news_version1_1.0.14"); ?></h3>
			 <h4><?php print $translate->_("news_version1_1.0.14_date"); ?></h4>
			 <p><?php print $translate->_("news_version1_1.0.14_content_1"); ?></p>
	      </div>
		 
		   <div class="row">
			
			 <h3><?php print $translate->_("news_version1_1.0.13"); ?></h3>
			 <h4><?php print $translate->_("news_version1_1.0.13_date"); ?></h4>
			 <p><?php print $translate->_("news_version1_1.0.13_content_1"); ?></p>
	      </div>
		  
		  <div class="row">
			
			 <h3><?php print $translate->_("news_version1_1.0.12"); ?></h3>
			 <h4><?php print $translate->_("news_version1_1.0.12_date"); ?></h4>
			 <p><?php print $translate->_("news_version1_1.0.12_content_1"); ?></p>
			 <p><?php print $translate->_("news_version1_1.0.11_content_3"); ?>
			 <a href="<?php echo $this->url(array('lang'=>$translate->getLocale(),'controller'=>'contact','action'=>'form'),'default', null, true);?>"><?php print $translate->_("news_version1_1.0.7_content_5"); ?></a>
			</p>
	      </div>
		  <div class="row">
			 <h3><?php print $translate->_("news_version1_1.0.11"); ?></h3>
			 <h4><?php print $translate->_("news_version1_1.0.11_date"); ?></h4>
			 <p><?php print $translate->_("news_version1_1.0.11_content_1"); ?></p>
			 <p><?php print $translate->_("news_version1_1.0.11_content_2"); ?></p>
			 <p><?php print $translate->_("news_version1_1.0.11_content_3"); ?>
			 <a href="<?php echo $this->url(array('lang'=>$translate->getLocale(),'controller'=>'contact','action'=>'form'),'default', null, true);?>"><?php print $translate->_("news_version1_1.0.7_content_5"); ?></a>
			</p>
		 </div>
		 
		 <div class="row">
			
			 <h3><?php print $translate->_("news_version1_1.0.7"); ?></h3>
			 <h4><?php print $translate->_("news_version1_1.0.7_date"); ?></h4>
			 <p><?php print $translate->_("news_version1_1.0.7_content_1"); ?></p>
			 <p><?php print $translate->_("news_version1_1.0.7_content_2"); ?></p>
			 <p><?php print $translate->_("news_version1_1.0.7_content_3"); ?></p>
			 <p><?php print $translate->_("news_version1_1.0.7_content_6"); ?></p>
			 <p><?php print $translate->_("news_version1_1.0.7_content_4"); ?>
			 <a href="<?php echo $this->url(array('lang'=>$translate->getLocale(),'controller'=>'contact','action'=>'form'),'default', null, true);?>"><?php print $translate->_("news_version1_1.0.7_content_5"); ?></a>
			</p>
		 </div>
		  


</div>