
 <?php $translate=Zend_Registry::get('Zend_Translate'); ?>
 <div class="panel detail">

    <div class="row">
         <div class="column">

             <div class="textBlock">
              <h2><?php print $translate->_("zumbaleh_desc_is_easy_header"); ?></h2> 

              <p><?php print $translate->_("zumbaleh_desc_is_easy_content1"); ?></p>
              <p><?php print $translate->_("zumbaleh_desc_is_easy_content2"); ?> <br/>
                 <?php print $translate->_("zumbaleh_desc_is_easy_content3"); ?><br>
                 <?php print $translate->_("zumbaleh_desc_is_easy_content4"); ?></p>
  
            </div>
         </div>
         <div class="column">
             <div class="textBlock">
              <h2><?php print $translate->_("zumbaleh_desc_is_social_header"); ?></h2>
              <p><?php print $translate->_("zumbaleh_desc_is_social_content1"); ?></p>
             
  
            </div>
         </div>

     </div>


 </div>
 <?php if($translate->getLocale()!="en"){ ?>
     <hr/>

      <div class="panel detail">

    <div class="row">
         <div class="column">

             <div class="textBlock">
              <h2><?php print $translate->_("zumbaleh_desc_is_interaction_header"); ?></h2> 

              <p><?php print $translate->_("zumbaleh_desc_is_interaction_content1"); ?></p>

            </div>
         </div>
         <div class="column">
             <div class="textBlock">
              <h2><?php print $translate->_("zumbaleh_desc_is_sms_im_header"); ?></h2> 

              <p><?php print $translate->_("zumbaleh_desc_is_sms_im_content1"); ?>
              </p>
              <p><?php print $translate->_("zumbaleh_desc_is_sms_im_content2"); ?></p>
             
  
            </div>
         </div>

     </div>


 </div>
     <hr/>
      <div class="panel detail">

    <div class="row">
         <div class="column">

             <div class="textBlock">
              <h2><?php print $translate->_("zumbaleh_desc_is_secure_header"); ?></h2> 

              <p><?php print $translate->_("zumbaleh_desc_is_secure_content1"); ?></p>

  
            </div>
         </div>
         <div class="column">
             <div class="textBlock">
              <h2><?php print $translate->_("zumbaleh_desc_is_multisesion_header"); ?></h2> 

              <p><?php print $translate->_("zumbaleh_desc_is_multisesion_content1"); ?></p>
             
  
            </div>
         </div>

     </div>

 </div>
  <hr/>
        <div class="panel detail">

    <div class="row">
         <div class="column">

             <div class="textBlock">
              <h2><?php print $translate->_("zumbaleh_desc_is_nfc_header"); ?></h2> 

              <p><?php print $translate->_("zumbaleh_desc_is_nfc_content1"); ?></p>

  
            </div>
         </div>
         <div class="column">
             <div class="textBlock">
              <h2><?php print $translate->_("zumbaleh_desc_is_and_more_header"); ?></h2> 

              <p><?php print $translate->_("zumbaleh_desc_is_and_more_content1"); ?></p>
             
  
            </div>
         </div>

     </div>

     <?php } ?>

 </div>
    