<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>Spoora</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Cache-Control" content="no-cache" />
<link rel="icon" href="favicon.png" type="image/x-icon" />
<!--link rel="shortcut icon" href="favicon.png" type="image/x-icon" /-->

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl('body1.css'); ?>" />
<script type="text/JavaScript" src="<?php /*echo $this->baseUrl('javascripts/jquery-1.5.min.js'); */?>"></script>

</head>

<body>



<div id="mainContent">
 <?php echo $this->layout()->content ?>

  <div id="footer"><?php echo  $this->render('footer.phtml') ?>
<!-- end #footer --></div>
<!-- end #mainContent --></div>

</body>
</html>